name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: [do-something]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  echo_passed_data:
    runs-on: windows-latest
    steps:
      - run: echo ${{ github.event.client_payload.sha }}
