name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: [do-something]
    branches: 
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
 
  nothing:
     runs-on: macos-latest
