name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: [do-something]
    branches: 
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
 
  echo_passed_data:
    runs-on: windows-latest
    steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
