# This is a basic workflow to help you get started with Actions

name: Create RC branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branchs
on:
  schedule:
    - cron: 5 * * * *

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  create_rc_branch:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    
    steps:
     - uses: actions/checkout@v1
     - uses: extenda/actions/gcp-secret-manager@v0
       with:
         service-account-key: ${{ secrets.SECRET_AUTH }}
         secrets: |
           ORG_TOKEN: github-token

     - uses: peterjgrainger/action-create-branch@v1.0.0
       env:
         GITHUB_TOKEN: ${{ env.ORG_TOKEN }}
       with:
         branch: 'schedule-test-branch'
    